# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_to_text_pb2 as voice__to__text__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_to_text_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceToTextHandlerStub(object):
    """This becomes the base class that will implement the rpc calls
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeVoice = channel.unary_unary(
                '/VoiceToTextComponents.VoiceToTextHandler/TranscribeVoice',
                request_serializer=voice__to__text__pb2.VttRequest.SerializeToString,
                response_deserializer=voice__to__text__pb2.VttResponse.FromString,
                _registered_method=True)


class VoiceToTextHandlerServicer(object):
    """This becomes the base class that will implement the rpc calls
    """

    def TranscribeVoice(self, request, context):
        """This will be the method that client will call and pass in the request, then server will implement what to do with the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceToTextHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeVoice': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeVoice,
                    request_deserializer=voice__to__text__pb2.VttRequest.FromString,
                    response_serializer=voice__to__text__pb2.VttResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VoiceToTextComponents.VoiceToTextHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VoiceToTextComponents.VoiceToTextHandler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceToTextHandler(object):
    """This becomes the base class that will implement the rpc calls
    """

    @staticmethod
    def TranscribeVoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VoiceToTextComponents.VoiceToTextHandler/TranscribeVoice',
            voice__to__text__pb2.VttRequest.SerializeToString,
            voice__to__text__pb2.VttResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
