# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_to_text.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_to_text.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13voice_to_text.proto\x12\x15VoiceToTextComponents\"%\n\nVttRequest\x12\x17\n\x0f\x61udio_file_path\x18\x01 \x01(\t\"$\n\x0bVttResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2n\n\x12VoiceToTextHandler\x12X\n\x0fTranscribeVoice\x12!.VoiceToTextComponents.VttRequest\x1a\".VoiceToTextComponents.VttResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_to_text_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VTTREQUEST']._serialized_start=46
  _globals['_VTTREQUEST']._serialized_end=83
  _globals['_VTTRESPONSE']._serialized_start=85
  _globals['_VTTRESPONSE']._serialized_end=121
  _globals['_VOICETOTEXTHANDLER']._serialized_start=123
  _globals['_VOICETOTEXTHANDLER']._serialized_end=233
# @@protoc_insertion_point(module_scope)
